<div class="row">
    <div class="col-8 mb-3">
        <h1>Agendamentos</h1>
    </div>
    <div class="col-4">
        <a href="<?= route('tattooists.appointments.new') ?>" class="btn btn-outline-primary">
            <i class="fe fe-plus"></i>
            Registrar Agendamento
        </a>
    </div>
</div>

<table class="table">
    <thead>
        <th>ID</th>
        <th>Date</th>
        <th>User</th>
        <th></th>
    </thead>
    <tbody>
        <?php if (!empty($appointments)) : ?>
        <?php foreach ($appointments as $appointment) : ?>
            
            <tr>
                <td><a href="<?= route('tattooists.appointments.show', ['id' => $appointment->id]) ?>">#<?= $appointment->id ?></a></td>
                <td><?= $appointment->date ?></td>
                <td><?= $appointment->user->name ?></td>
                <td>
                    <div class="d-flex flex-row-reverse">
                        <form action="<?= route('appointments.destroy', ['id' => $appointment->id]) ?>" method="POST" class="m-0">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-link"><i class="bi bi-archive"></i></button>
                        </form>
                        <a href="<?= route('appointments.edit', ['id' => $appointment->id]) ?>" class="btn btn-link pe-0">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php else : ?>
            <tr>
                <td colspan="3">Sem Agendamentos registrados</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>
