<form action="<?= route('tattooists.appointments.create') ?>" method="POST" class="<?= $appointment->hasErrors() ? '' : 'was-validated' ?>" novalidate>
    <div class="mb-3">
        
    <label for="date" class="form-label">Data do agendamento:</label>
        <input type="datetime-local" value="<?= $appointment->date ?>" name="appointment[date]" class="form-control" id="date" required>
        <div class="invalid-feedback"><?= $appointment->errors('date') ? $appointment->errors('date') : '' ?></div>
        
        <label for="size" class="form-label">Tamanho:</label>
        <select name="appointment[size]" class="form-select" aria-label="Selecione o tamanho">
            <option selected disabled>Clique para selecionar os tamanhos</option>
            <option value="pequeno">Pequeno (20x20 até 30x30)</option>
            <option value="medio">Médio (30x30 até 40x40)</option>
            <option value="grande">Grande (40x40 até 50x50)</option>
        </select>
        <div class="invalid-feedback"><?= $appointment->errors('size') ? $appointment->errors('size') : '' ?></div>

        <label for="location" class="form-label">Local da tatuagem:</label>
        <select name="appointment[location]" class="form-select" id="location" aria-label="Selecione o local">
            <option selected disabled>Clique para selecionar o local</option>
            <option value="braco">braço</option>
            <option value="antebraco">antebraço</option>
            <option value="perna">perna</option>
            <option value="barriga">barriga</option>
            <option value="outros">outros</option>
        </select>
        <div class="invalid-feedback"><?= $appointment->errors('location') ? $appointment->errors('location') : '' ?></div>
        
        <label for="status" class="form-label">Status:</label>
        <select name="appointment[status]" class="form-select" id="status" aria-label="Selecione o status" required>
            <option selected disabled>Clique para selecionar o local</option>
            <option value="pendente">pendente</option>
            <option value="confirmado">confirmado</option>
            <option value="cancelado">cancelado</option>
            <option value="completado">completado</option>
        </select>
        <div class="invalid-feedback"><?= $appointment->errors('status') ? $appointment->errors('status') : '' ?></div>
        
        <label for="client" class="form-label">Cliente:</label>
        <select name="appointment[users_id]" class="form-select" id="client" aria-label="Selecione o cliente" required>
            <option selected disabled>Clique para selecionar o Cliente</option>
            <?php foreach ($users as $user) : ?>
                <option value="<?= $user->id ?>"><?= $user->name ?></option>
            <?php endforeach; ?>
        </select>
        <div class="invalid-feedback"><?= $appointment->errors('users_id') ? $appointment->errors('users_id') : '' ?></div>
    </div>

    <button type="submit" class="btn btn-primary">Registrar</button>
</form>